"""Fix relacion cancha timeslot

Revision ID: 3e6ded6ccdf9
Revises: bf5c9bb8fd5d
Create Date: 2025-11-05 19:23:03.901607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6ded6ccdf9'
down_revision = 'bf5c9bb8fd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslot_definicion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('paso_minutos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=120), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'NO_ASISTIO', name='reserva_estado', native_enum=False), nullable=False),
    sa.Column('fuente', sa.Enum('WEB', 'PRESENCIAL', 'TELEFONICA', name='fuente_reserva', native_enum=False), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('senia_monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('senia_pagada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeslot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'RESERVADO', 'BLOQUEADO', 'NO_GENERADO', name='timeslot_estado', native_enum=False), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva_timeslot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timeslot_id')
    )
    with op.batch_alter_table('reserva_timeslot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserva_timeslot_reserva_id'), ['reserva_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva_timeslot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserva_timeslot_reserva_id'))

    op.drop_table('reserva_timeslot')
    op.drop_table('timeslot')
    op.drop_table('reserva')
    op.drop_table('timeslot_definicion')
    # ### end Alembic commands ###
