"""Initial migration

Revision ID: bf5c9bb8fd5d
Revises: 
Create Date: 2025-11-04 18:46:11.878140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c9bb8fd5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('piso', sa.String(length=10), nullable=True),
    sa.Column('depto', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('provincia', sa.String(length=80), nullable=True),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('cp', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    op.drop_table('direccion')
    # ### end Alembic commands ###
