"""Agregar tabla club_horario

Revision ID: c9450434d519
Revises: cbb0c045b5c7
Create Date: 2025-11-10 17:51:13.750996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9450434d519'
down_revision = 'cbb0c045b5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_horario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('LUN', 'MAR', 'MIE', 'JUE', 'VIE', 'SAB', 'DOM', name='dia_semana', native_enum=False), nullable=False),
    sa.Column('abre', sa.Time(), nullable=False),
    sa.Column('cierra', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_horario')
    # ### end Alembic commands ###
