"""agregar campo ganador a Partido

Revision ID: fc69ee2062e5
Revises: d32506d48ddd
Create Date: 2025-11-13 17:56:07.420439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc69ee2062e5'
down_revision = 'd32506d48ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ganador_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_partido_ganador_id", 'equipo', ['ganador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_constraint("fk_partido_ganador_id", type_='foreignkey')
        batch_op.drop_column('ganador_id')

    # ### end Alembic commands ###
